# ----------------------
# DB 연결
# ----------------------
spring.jpa.database = MYSQL
spring.jpa.show-sql = true

# ----------------------
# DB driver 설정
# DB URL 설정
# 연결 잘 됐는지 확인용 test query  SELECT 1
# under_score로 작성된 컬럼명을 camelCase로 바꿔줄지 여부
# ----------------------
spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.jdbc-url=jdbc:mysql://localhost:3306/db1?characterEncoding=UTF-8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.hikari.username=admin
spring.datasource.hikari.password=a164922!#
spring.datasource.hikari.connection-test-query=SELECT 123
mybatis.configuration.map-underscore-to-camel-case=true

# --------------------------------------------------------------------------------------------------------------
# mapper xml의 경로를 설정
# mybatis 매핑 type을 짧게 쓰기 위한 설정
# mapper.xml에서 resultType을 지정할 때 com.example.test.vo.TestVo 대신 TestVo로 간략히 할 수 있다.
# mapper.xml 위치 지정 # **은 하위 폴더 레벨에 상관없이 모든 경로를 뜻하며, *는 아무 이름이나 와도 된다는것을 뜻합니다.
# --------------------------------------------------------------------------------------------------------------
mybatis.type-aliases-package= com.backend.seperate.dto
mybatis.mapper-locations=mybatis/mapper/**/*.xml


#[JPA]
spring.jpa.open-in-view=true
#ddl query 자동생성
spring.jpa.hibernate.ddl-auto=create

#변수명 그대로 필드 생성                                                     
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#JPA의 기본 넘버링 전략을 따라가지 않음
spring.jpa.hibernate.use-new-id-generator-mappings=false

# Jackson
spring.jackson.serialization.fail-on-empty-beans=false

# Logging
logging.level.org.springframework.web=DEBUG


# ----------------
#토큰
#-----------------
logging.level.com.andy=trace
# 토큰 유효기간 (min)
#jwt.expmin=5
# 토큰 생성에 사용할 salt
#jwt.salt=MYSALT

# 파일 업로드 directory
# file.upload.directory = D

server.port=8085
# server.ssl.key-store=D:/vuejsSpring/practiceone/keystore.jks
# server.ssl.key-store-type=jks
# jks 암호 지정
#server.ssl.key-store-password=123456
#server.ssl.key-password=1234567
# (필요시) Alias 명 지정. CSR 자동 생성시에는 CN 명
#server.ssl.key-alias=sslkeytest
#server.ssl.trust-store= # (필요시) "sslcert.co.kr.jks" 지정. CSR 직접 생성시에는, 루트/체인 스토어 파일 지정
#server.ssl.trust-store-password=xxxxxxx # (필요시) jks 암호