server:
    port: 8085

jwt:
    header: Authorization
    #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
    #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    token-validity-in-seconds: 3600

spring:
  profiles: 
    active: dev


  # DB 설정
  datasource:
    # 기본 설정
    # url: jdbc:mysql://localhost:3306/db1?characterEncoding=UTF-8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    # driver-class-name: com.mysql.jdbc.Driver
    
    hikari:
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/db1?characterEncoding=UTF-8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      username: root
      password: dnjstjr26
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      max-lifetime: 240000
      maximum-pool-size: 20

# jpa 설정
  jpa:
    hibernate: # hibernate 사용 설정
        ddl-auto: update # create,create-drop,update,none
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        #show_sql: true
        #format_sql: true
  #defer-datasource-initialization: true

# Log 설정  
logging:
  level:
    root: INFO # TRACE, DEBUG, INFO, WARN, ERROR 
    com:
      zaxxer:
        hikari: INFO
    javax:
      sql:
        DataSource: OFF
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: INFO
      sqlonly: INFO
      sqltiming: OFF
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO